KS-1-4 print data from 5-th lesson
Nemirich/KotlinSprint pull request #5
Opened 2023-05-17 20:02 UTC by Nemirich

Очень костыльно сделал

Нашел в инете как тображать формат даты/времени на данный момент времени 
Но как отобразить просто секунды - не нашел (в формате "00", а не "0")

Возможно, нужно было больше покапаться
Но я подумал что завтра новый урок и лучше тебе отправить как есть 
Чтоб завтра за новые задания сесть сразу 

Поправь меня, если поступил неправильно

Спасибо!

2023-05-17 20:51 UTC, ievetrov requested changes

2023-05-17 20:51 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    println("$minutes : $secondsInSpace1$secondsInSpace2")
так как задачи под номером 5 "со звездочкой", нужно более продвинутое решение) либо не страшно, если вернешься к этой задаче позже

попробуй посмотреть как работает форматирование строк с помощью String.format()

2023-05-17 20:51 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +fun main () {
пробел

2023-05-17 20:51 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val ostatok = seconds%secondsInMinute // проверяем, что делится без остатка
арифметические знаки обосабливаются пробелами согласно конвенции стиля Котлин

2023-05-23 10:56 UTC, Nemirich commented
Не понял зачем он эту штуку подтянул
![image](https://github.com/Nemirich/KotlinSprint/assets/133893209/0d410601-4853-48cb-a1e8-999a0e51970f)

Типа потому что я использовал формулу "из библиотеки?"

2023-05-23 18:32 UTC, ievetrov commented
> Не понял зачем он эту штуку подтянул ![image](https://user-images.githubusercontent.com/133893209/240242944-0d410601-4853-48cb-a1e8-999a0e51970f.png)
> 
> Типа потому что я использовал формулу "из библиотеки?"

все верно. это "импорты" классов из стандартной библиотеки, чтобы ты мог воспользоваться функциями и свойствами. все эти вещи хранятся в SDK, который ты выбирал при создании проекта. 

все эти библиотеки , которые используются в проекте, можно увидеть слева в иерархии файлов. импорт как правило подтягивается автоматически, когда знаешь какой метод или свойство вызвать

<img width="345" alt="Снимок экрана 2023-05-23 в 21 30 56" src="https://github.com/Nemirich/KotlinSprint/assets/34489023/ba91f63b-7baf-4ca2-bcfe-eda87a9cbcfe">

2023-05-23 18:33 UTC, ievetrov requested changes
все ок! осталась пара стилистических правок)

2023-05-23 18:33 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val ostatok = seconds%secondsInMinute // проверяем, что делится без остатка
не исправлено)
добавь плз пробелы вокруг знака %

2023-05-23 18:33 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val minutes: Int = (seconds/secondsInMinute)
тут тоже нужны пробелы вокруг знака деления

2023-05-23 18:33 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
легальное решение, есть более распространенный способ)

использовать форматирование строки с помощью String.format(). выглядеть это может вот так
`val formatTime = String.format("%02d:%02d", minutes, seconds)`

для этого ты находишь сначала целое количество минут, затем остаток секунд, используя остаток от деления (будет 0). и вот при форматировании строки задается шаблон вывода по специальным правилам. в который отправляется переменная с секундами

2023-05-23 20:17 UTC, Nemirich commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
> легальное решение, есть более распространенный способ)
> 
> использовать форматирование строки с помощью String.format(). выглядеть это может вот так `val formatTime = String.format("%02d:%02d", minutes, seconds)`
> 
> для этого ты находишь сначала целое количество минут, затем остаток секунд, используя остаток от деления (будет 0). и вот при форматировании строки задается шаблон вывода по специальным правилам. в который отправляется переменная с секундами

Я пробовал что-то такое 
И мне выдавало четко ошибку что значение минут не может быть больше 60
А у нас 108 минут
И в задании написано вывести без количества часов, только в минутах и секундах

2023-05-23 20:33 UTC, Nemirich commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
В чем еще проблема
Я понял что согласно конценции языка Kortlin мы обязаны делать отступы при знаках арифметических знаках
НО
Если просто сделать отступ, то они получаются в формате "108 : 00"
А у нас по заданию пример: "108:00"

Поэтому вот я решил сделать вот так

2023-05-23 20:40 UTC, Nemirich commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
> легальное решение, есть более распространенный способ)
> 
> использовать форматирование строки с помощью String.format(). выглядеть это может вот так `val formatTime = String.format("%02d:%02d", minutes, seconds)`
> 
> для этого ты находишь сначала целое количество минут, затем остаток секунд, используя остаток от деления (будет 0). и вот при форматировании строки задается шаблон вывода по специальным правилам. в который отправляется переменная с секундами

Вот сейчас попробовал
И ошибку не выдает
<img width="621" alt="image" src="https://github.com/Nemirich/KotlinSprint/assets/133893209/7845ea60-ba0d-462b-ad49-07d8ed2653a8">

Значит я использовал что-то другое
Сейчас вспомню

2023-05-23 20:55 UTC, Nemirich commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
Блин, я помню что я делал ТОЧНО также
И он выдавал ошибку, что более 60 минут нельзя
А сейчас все спокойно работает
<img width="719" alt="image" src="https://github.com/Nemirich/KotlinSprint/assets/133893209/ff05a3d6-e04b-437f-ab44-dc6aab0dfbfd">

Наверняка я что-то путаю
И мб была какая-то чуть другая функция
Но я помню точно про ограничение в 60 минут))

2023-05-24 08:33 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
> Я пробовал что-то такое И мне выдавало четко ошибку что значение минут не может быть больше 60 А у нас 108 минут И в задании написано вывести без количества часов, только в минутах и секундах

судя по разнообразным экспериментальным импортам, которые были ранее, ты вероятно работал с объектами даты) поэтому могли всплыть некоторые ограничения. в нашем решении дат не касаемся вообще. только математика и форматирование строки

2023-05-24 08:35 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
SimpleDateFormat это тоже про парсинг даты (времени) из строки. Пока думаю не стоит так глубоко уходить) но конечно не запрещено разобраться в этом)

2023-05-24 08:40 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +import java.sql.Time
неиспользуемые импорты следует удалять (они подсвечиваются серым шрифтом)

2023-05-24 08:40 UTC, ievetrov commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val secondInTime = inValue.toString().padStart(n, '0')
если захочется поковыряться с форматированием дат, то также рекомендую обратить внимание на класс `LocalDateTime`

это аналог `SimpleDateFormat`, но из более свежего API. он решает ряд проблем старого подхода и более удобен (более интуитивно понятные функции внутри). с ним следует быть знакомым

2023-05-24 08:41 UTC, ievetrov requested changes
давай еще почистим импорты

2023-05-24 09:31 UTC, Nemirich commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +import java.sql.Time
Получается все вот эти подсвечиваются серым
Значит все и удалять
![image](https://github.com/Nemirich/KotlinSprint/assets/133893209/527bf61c-e012-4980-bb4b-003f1d196eff)

2023-05-25 13:12 UTC, ievetrov approved these changes
все верно) отлично!

2023-05-25 17:17 UTC, merged